# Generated by Django 5.2.17 on 2026-08-29 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('activity_type', models.CharField(choices=[('course_created', 'Course Ditambahkan'), ('course_updated', 'Course Diedit'), ('course_deleted', 'Course Dihapus'), ('participant_created', 'Peserta Ditambahkan'), ('participant_updated', 'Peserta Diedit'), ('participant_deleted', 'Peserta Dihapus'), ('course_completed', 'Course Selesai'), ('other', 'Lainnya')], default='other', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='courses.course')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='participants.participant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
